### ISSUE TITLE
ValueError: at position 2, opcode b'\x03' unknown

### ISSUE THREAD

**Issue by whitevamp** [mmaitre314/picklescan#18]
I went and installed this with pip

 and then went to run it and i get this error.
`picklescan --path G:/AI_Generation/stable-diffusion-webui-master/models/Stable-diffusion/
Unhandled exception
Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python310\lib\site-packages\picklescan\cli.py", line 70, in main
    scan_result = scan_directory_path(path)
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python310\lib\site-packages\picklescan\scanner.py", line 410, in scan_directory_path
    scan_result.merge(scan_bytes(file, file_path, file_ext))
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python310\lib\site-packages\picklescan\scanner.py", line 350, in scan_bytes
    return scan_pytorch(data, file_id)
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python310\lib\site-packages\picklescan\scanner.py", line 338, in scan_pytorch
    magic = get_magic_number(data)
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python310\lib\site-packages\picklescan\torch.py", line 77, in get_magic_number
    for opcode, args, _pos in genops(data):
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python310\lib\pickletools.py", line 2285, in _genops
    raise ValueError("at position %s, opcode %r unknown" % (
ValueError: at position 2, opcode b'\x03' unknown`

now if I run 
`picklescan --huggingface ykilcher/totally-harmless-model
https://huggingface.co/ykilcher/totally-harmless-model/resolve/main/pytorch_model.bin:archive/data.pkl: dangerous import '__builtin__ eval' FOUND
----------- SCAN SUMMARY -----------
Scanned files: 1
Infected files: 1
Dangerous globals: 1`
as you can see it returns ok.

**Comment by mmaitre314** [comment]
It looks like picklescan is trying to handle a file which is not a pickle file and does not realize it. Would you have instructions on how to setup folder `/stable-diffusion-webui-master/models/Stable-diffusion/` so I can try a repro?

Formatted callstack for future reference:
```
picklescan\cli.py, line 70,      in main scan_result = scan_directory_path(path) 
picklescan\scanner.py, line 410, in scan_directory_path scan_result.merge(scan_bytes(File, File_path, File_ext)) 
picklescan\scanner.py, line 350, in scan_bytes return scan_pytorch(data, File_id) 
picklescan\scanner.py, line 338, in scan_pytorch magic = get_magic_number(data) 
picklescan\torch.py, line 77,    in get_magic_number for opcode, args, _pos in genops(data): 
lib\pickletools.py, line 2285,   in _genops raise ValueError("at position %s, opcode %r unknown" % ( ValueError: at position 2, opcode b'\x03' unknown
```

**Comment by whitevamp** [comment]
> It looks like picklescan is trying to handle a file which is not a pickle file and does not realize it. Would you have instructions on how to setup folder `/stable-diffusion-webui-master/models/Stable-diffusion/` so I can try a repro?
> 
> Formatted callstack for future reference:
> 
> ```
> picklescan\cli.py, line 70,      in main scan_result = scan_directory_path(path) 
> picklescan\scanner.py, line 410, in scan_directory_path scan_result.merge(scan_bytes(File, File_path, File_ext)) 
> picklescan\scanner.py, line 350, in scan_bytes return scan_pytorch(data, File_id) 
> picklescan\scanner.py, line 338, in scan_pytorch magic = get_magic_number(data) 
> picklescan\torch.py, line 77,    in get_magic_number for opcode, args, _pos in genops(data): 
> lib\pickletools.py, line 2285,   in _genops raise ValueError("at position %s, opcode %r unknown" % ( ValueError: at position 2, opcode b'\x03' unknown
> ```
you mentioning that it was trying to handle a file but didnt know how to, made a light bulb go off, I have 98% hard links in there so i decided to run the scanner on the main folders, and  came out with this. ( hard links made no difference. )
G:\HuggingFace\RectalWorm\locons              scanned fine 
G:\HuggingFace\RectalWorm\models            ERROR: parsing pickle in G:\HuggingFace\RectalWorm\models\a1_v10_trainingData.zip: at position 7, opcode b'\xcf' unknown
----------- SCAN SUMMARY -----------
Scanned files: 9
Infected files: 0
Dangerous globals: 0          but did finish the scan. it got lost on that zip file and yes i know its not suppose to do anything with zip files.

now heres an error.

`picklescan --path G:\HuggingFace\RectalWorm\loras_new
ERROR: parsing pickle in G:\HuggingFace\RectalWorm\loras_new\Downloads.zip: at position 7, opcode b'\x00' unknown
Unhandled exception
Traceback (most recent call last):
  File "C:\Users\whitevamp\AppData\Local\Programs\Python\Python310\lib\site-packages\picklescan\cli.py", line 70, in main
    scan_result = scan_directory_path(path)
  File "C:\Users\whitevamp\AppData\Local\Programs\Python\Python310\lib\site-packages\picklescan\scanner.py", line 410, in scan_directory_path
    scan_result.merge(scan_bytes(file, file_path, file_ext))
  File "C:\Users\whitevamp\AppData\Local\Programs\Python\Python310\lib\site-packages\picklescan\scanner.py", line 350, in scan_bytes
    return scan_pytorch(data, file_id)
  File "C:\Users\whitevamp\AppData\Local\Programs\Python\Python310\lib\site-packages\picklescan\scanner.py", line 338, in scan_pytorch
    magic = get_magic_number(data)
  File "C:\Users\whitevamp\AppData\Local\Programs\Python\Python310\lib\site-packages\picklescan\torch.py", line 77, in get_magic_number
    for opcode, args, _pos in genops(data):
  File "C:\Users\whitevamp\AppData\Local\Programs\Python\Python310\lib\pickletools.py", line 2285, in _genops
    raise ValueError("at position %s, opcode %r unknown" % (
ValueError: at position 6, opcode b'\x1a' unknown`

now all those huggingface dir are direct mirrors of whats on the site. [https://huggingface.co/RectalWorm](url)

with all of that done, i decided to start doing a process of elimination, witch surprisingly didnt take long at all, and this is the file thats causing the issue.
[https://huggingface.co/RectalWorm/loras_new/resolve/main/Owl_Mage_no_background.pt](url)
hope this helps.

**Comment by mmaitre314** [comment]
The file starts with `89  50  4e  47  0d  0a  1a  0a`, which is a PNG file header (in spite of the PyTorch .pt extension). The fix is likely to skip that file.

**Comment by whitevamp** [comment]
> The file starts with `89 50 4e 47 0d 0a 1a 0a`, which is a PNG file header (in spite of the PyTorch .pt extension). The fix is likely to skip that file.

ok thank you
