### ISSUE TITLE
Pickle is file extension agnostic 

### ISSUE THREAD

**Issue by moohax** [mmaitre314/picklescan#5]
I saw somewhere another list of file extensions that huggingface will scan for - but a pickle file can have an arbitrary extension.  I'm not even sure you need a file extension...

```python
_pytorch_file_extensions = {".bin", ".pt", ".pth", ".ckpt"}
_pickle_file_extensions = {".pkl", ".pickle", ".joblib", ".dat"}
_zip_file_extensions = {".zip", ".npz"}
```

Maybe you could scan for magic bytes for additional coverage? (Pickle files can also be mangled quite a bit - according to this [bug report](https://bugs.astron.com/view.php?id=264))

**Comment by mmaitre314** [comment]
We hit issues with Pickle not having great magic bytes to work with. Protocol versions 0 & 1 are lacking magic bytes altogether and Versions 2+ only seem to have the `PROTO` opcode which can kind of be used as magic bytes. The most reliable way to check a file is a Pickle so far looks like reading the whole file and checking whether `genops()` throws. Not super efficient, but could be added as an option in case users know better.

**Comment by moohax** [comment]
And you have files that look like this:

```
cos
system
(S'calc'
tR.
```

CodeQL rules maybe? Scan for imports of known dangerous libs - like when MS phased out BinaryFormatter in dotnet.
