### ISSUE TITLE
EICAR Test

### ISSUE THREAD

**Issue by moohax** [mmaitre314/picklescan#6]
Have the ability to create put the [EICAR](https://en.wikipedia.org/wiki/EICAR_test_file) string in a pickle file, such that you could see what existing tools might already be scanning pickle files. From this you could potentially build in some detection and alerting with existing EDRs etc.

**Comment by mmaitre314** [comment]
If I understand the scenario correctly, this sounds more like Pickle generation than Pickle scanning. Maybe something along those lines:
```python
import pickle
pickle.dumps("X5O!P%...-TEST-FILE!$H+H*")
```

**Comment by moohax** [comment]
Yeah - something along those lines. I was thinking of something like a canary. You'd maybe (hopefully) find out that Defender or some other product might already be looking at ML and ML related files.
